# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'isyumi_p2p_swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'FirebaseUI', '~> 4.0'
  pod 'FirebaseUI/Auth'

  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/Twitter'
  pod 'FirebaseUI/Phone'
  pod 'SkyWay-iOS-SDK'

  # Pods for isyumi_p2p_swift

  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'

  target 'isyumi_p2p_swiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
